### ISSUE TITLE
I think I figured it out!

### ISSUE THREAD

**Issue by divineaverage** [divineaverage/P6_Sauce#1]
So I changed all the imports back to require, had a whole different issue. Changed them back to imports and then added ".js" to the end of all the imported files (out of desperation), and for some reason it seems to have worked. The only issue remaining is that jwt is apparently not friends with ES6 so I can't figure out how to make that work now. Any thoughts? Hope the trip is going well!

**Comment by AccessiT3ch** [comment]
@divineaverage Ah it looks like the issue now iis that you're mixing ES6 `import .. from '..'` with commonJS `module.export = ...`. Instead, declare/export the middleware funciton with ES6 `export const ... = ...`. In this case your auth.js might have something that looks like:

```js
import jwt from 'jsonwebtoken';

export const SOME_MAGIC_STRING = 'something'; // I like to export just about everything from modules

export const authorize = (req, res, next) => {
  ...
}

export default authorize;
```

It's not necessary to export both the `const` and the `default`, but I like doing it so it's always easy to import in other modules. Exported constants can be imported into other modules with brackets, like:

```js
import { SOME_MAGIC_STRING, authorize } from './path/to/auth';
```

While exported `defaults` are imported without the brackets, but can we can still import anything we like:

```js
import auth, { SOME_MAGIC_STRING } from './path/to/auth';
```

If no `default` is exported from the module, we can still import everything as a module like:

```js
import * as auth from `./path/to/auth`;
```
